version: '2'
services:
  main:
    build: .
    volumes:
      - ./src:/home/node/archive/src
      - ./config:/home/node/archive/config
      - ./wiki:/home/node/archive/wiki
    command: 'npm run dev'
