version: '2'
services:
  main:
    build: .
    volumes:
      - ./src:/home/node/archive/src
      - ./test:/home/node/archive/test
      - ./config:/home/node/archive/config
      - ./wiki:/home/node/archive/wiki
    command: 'npm run debug'
    ports:
      - 9229:9229
      - 9230:9230
      - '${PORT}:${PORT}'
    expose:
        - 9229
        - 9230

  # invoice_worker:
  #   build: .
  #   volumes:
  #     - ./src:/home/node/archive/src
  #     - ./test:/home/node/archive/test
  #     - ./config:/home/node/archive/config
  #   command: 'npm run worker:invoice'
  #   ports:
  #     - 9230:9230
  #   expose:
  #       - 9230
  #   depends_on:
  #       - rabbitmq 
      
