type: object
properties:
  event:
    version: string
    transactionId: string
    document:
      customerId: string
      supplierId: string
      msgType: string
example: !include ../examples/TransactionEventDocument.json
