'use strict';

module.exports = {
  ERR_INDEX_DOES_NOT_EXIST: 'ERR_INDEX_DOES_NOT_EXIST',
  ERR_SRC_INDEX_DOES_NOT_EXIST: 'ERR_SRC_INDEX_DOES_NOT_EXIST',
  ERR_INDEX_OPEN_FAILED: 'ERR_INDEX_OPEN_FAILED'
};

